logging.level:
  com.cb.berryz: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vader
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  vader:
    room:
      baseurl: http://codeberry.co.jp/vader/room/